name: 'RegEx Issue Title Labeler'
description: 'Labels issues automagically based on their title & body'
author: 'GitHub'
inputs:
  repo-token:
    description: 'The GITHUB_TOKEN secret'
    required: true
  configuration-path:
    description:  'Path to the labeler.yml configuration file'
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
branding:
  icon: 'activity'  
  color: 'blue'
